name: cyd_aquarium_mobile
description: Mobilny panel sterownika cydAkwarium dla Androida i iOS.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^11.0.2
  flutter_reactive_ble: ^5.5.0
  permission_handler: ^12.0.3
  shared_preferences: ^2.5.5
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
